/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Blood-Joker
 */
public class RoomChoose extends javax.swing.JFrame {

    /**
     * Creates new form RoomChoose
     */
    public RoomChoose() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        button301 = new javax.swing.JButton();
        button302 = new javax.swing.JButton();
        button303 = new javax.swing.JButton();
        button304 = new javax.swing.JButton();
        button305 = new javax.swing.JButton();
        button201 = new javax.swing.JButton();
        button202 = new javax.swing.JButton();
        button203 = new javax.swing.JButton();
        button204 = new javax.swing.JButton();
        button205 = new javax.swing.JButton();
        button101 = new javax.swing.JButton();
        button102 = new javax.swing.JButton();
        button103 = new javax.swing.JButton();
        button104 = new javax.swing.JButton();
        button105 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        door301 = new javax.swing.JLabel();
        door304 = new javax.swing.JLabel();
        door302 = new javax.swing.JLabel();
        door303 = new javax.swing.JLabel();
        door305 = new javax.swing.JLabel();
        door201 = new javax.swing.JLabel();
        door203 = new javax.swing.JLabel();
        door105 = new javax.swing.JLabel();
        door103 = new javax.swing.JLabel();
        door202 = new javax.swing.JLabel();
        door104 = new javax.swing.JLabel();
        door101 = new javax.swing.JLabel();
        door102 = new javax.swing.JLabel();
        door204 = new javax.swing.JLabel();
        door205 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147, 2147));
        setPreferredSize(new java.awt.Dimension(815, 1186));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 3276));

        jLabel1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jLabel1.setText("Choose the room you want!");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jButton1.setText("Single room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jButton2.setText("Double room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        button301.setBackground(new java.awt.Color(0, 255, 255));
        button301.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button301.setText("301");
        button301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button301ActionPerformed(evt);
            }
        });

        button302.setBackground(new java.awt.Color(0, 255, 255));
        button302.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button302.setText("302");
        button302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button302ActionPerformed(evt);
            }
        });

        button303.setBackground(new java.awt.Color(0, 255, 255));
        button303.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button303.setText("303");
        button303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button303ActionPerformed(evt);
            }
        });

        button304.setBackground(new java.awt.Color(0, 255, 255));
        button304.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button304.setText("304");
        button304.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button304ActionPerformed(evt);
            }
        });

        button305.setBackground(new java.awt.Color(0, 255, 255));
        button305.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button305.setText("305");
        button305.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button305ActionPerformed(evt);
            }
        });

        button201.setBackground(new java.awt.Color(255, 102, 102));
        button201.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button201.setText("201");
        button201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button201ActionPerformed(evt);
            }
        });

        button202.setBackground(new java.awt.Color(255, 102, 102));
        button202.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button202.setText("202");
        button202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button202ActionPerformed(evt);
            }
        });

        button203.setBackground(new java.awt.Color(255, 102, 102));
        button203.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button203.setText("203");
        button203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button203ActionPerformed(evt);
            }
        });

        button204.setBackground(new java.awt.Color(255, 102, 102));
        button204.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button204.setText("204");
        button204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button204ActionPerformed(evt);
            }
        });

        button205.setBackground(new java.awt.Color(255, 102, 102));
        button205.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button205.setText("205");
        button205.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button205ActionPerformed(evt);
            }
        });

        button101.setBackground(new java.awt.Color(0, 255, 51));
        button101.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button101.setText("101");
        button101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button101ActionPerformed(evt);
            }
        });

        button102.setBackground(new java.awt.Color(0, 255, 51));
        button102.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button102.setText("102");
        button102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button102ActionPerformed(evt);
            }
        });

        button103.setBackground(new java.awt.Color(0, 255, 51));
        button103.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button103.setText("103");
        button103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button103ActionPerformed(evt);
            }
        });

        button104.setBackground(new java.awt.Color(0, 255, 51));
        button104.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button104.setText("104");
        button104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button104ActionPerformed(evt);
            }
        });

        button105.setBackground(new java.awt.Color(0, 255, 51));
        button105.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        button105.setText("105");
        button105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button105ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel3.setText("$200/night");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel4.setText("$250/night");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sroom.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/droom.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel6.setText("or");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel7.setText("Room Number");

        door301.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door304.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door305.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door203.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N
        door103.setToolTipText("");

        door202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door204.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        door205.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(button201, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(door301, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(door305, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(button205, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button302, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(door302, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(door303)
                                .addComponent(jLabel6)
                                .addComponent(button303, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(button304, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button305, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(door204)
                                        .addComponent(door304)
                                        .addComponent(button204, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(door104))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(door205, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(door105, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(door101)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(door102))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(button101, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button102, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(button202, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(door201)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                    .addComponent(door202)))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button203, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(door203, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(door103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(40, 40, 40)
                            .addComponent(button104, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(button105, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(32, 32, 32)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button301, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(567, 567, 567)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button302, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button304, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button305, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button303)
                                .addComponent(button301)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(door301)
                                    .addComponent(door302)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(door304))))
                    .addComponent(door305)
                    .addComponent(door303))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button201)
                    .addComponent(button202)
                    .addComponent(button203)
                    .addComponent(button204)
                    .addComponent(button205))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(door201)
                            .addComponent(door202)
                            .addComponent(door203)
                            .addComponent(door205, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button101)
                            .addComponent(button102)
                            .addComponent(button104)
                            .addComponent(button105))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(door101)
                            .addComponent(door102)
                            .addComponent(door104)
                            .addComponent(door105)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(door204)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button103)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(door103)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button105ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button105ActionPerformed

    private void button104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button104ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button104ActionPerformed

    private void button103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button103ActionPerformed
        // TODO add your handling code here:
        SingleRoomDate a = new SingleRoomDate();
        a.run();
    }//GEN-LAST:event_button103ActionPerformed

    private void button102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button102ActionPerformed
        // TODO add your handling code here:
        SingleRoomDate a = new SingleRoomDate();
        a.run();
    }//GEN-LAST:event_button102ActionPerformed

    private void button101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button101ActionPerformed
        // TODO add your handling code here:
        SingleRoomDate a = new SingleRoomDate();
        a.run();
    }//GEN-LAST:event_button101ActionPerformed

    private void button205ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button205ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button205ActionPerformed

    private void button204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button204ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button204ActionPerformed

    private void button203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button203ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button203ActionPerformed

    private void button202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button202ActionPerformed
        // TODO add your handling code here:
        SingleRoomDate a = new SingleRoomDate();
        a.run();
    }//GEN-LAST:event_button202ActionPerformed

    private void button201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button201ActionPerformed
        // TODO add your handling code here:
        SingleRoomDate a = new SingleRoomDate();
        a.run();
    }//GEN-LAST:event_button201ActionPerformed

    private void button305ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button305ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button305ActionPerformed

    private void button304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button304ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button304ActionPerformed

    private void button303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button303ActionPerformed
        // TODO add your handling code here:
        DoubleRoomDate a = new DoubleRoomDate();
        a.run();
    }//GEN-LAST:event_button303ActionPerformed

    private void button302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button302ActionPerformed
        // TODO add your handling code here:
        SingleRoomDate a = new SingleRoomDate();
        a.run();
    }//GEN-LAST:event_button302ActionPerformed

    private void button301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button301ActionPerformed
        // TODO add your handling code here:
        SingleRoomDate a = new SingleRoomDate();
        a.run();
    }//GEN-LAST:event_button301ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        button301.setVisible(false);
        button302.setVisible(false);
        button201.setVisible(false);
        button202.setVisible(false);
        button101.setVisible(false);
        button102.setVisible(false);
        button103.setVisible(false);
        button303.setVisible(true);
        button304.setVisible(true);
        button305.setVisible(true);
        button203.setVisible(true);
        button204.setVisible(true);
        button205.setVisible(true);
        button104.setVisible(true);
        button105.setVisible(true);
        door301.setVisible(false);
        door302.setVisible(false);
        door201.setVisible(false);
        door202.setVisible(false);
        door101.setVisible(false);
        door102.setVisible(false);
        door103.setVisible(false);
        door303.setVisible(true);
        door304.setVisible(true);
        door305.setVisible(true);
        door203.setVisible(true);
        door204.setVisible(true);
        door205.setVisible(true);
        door104.setVisible(true);
        door105.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        button301.setVisible(true);
        button302.setVisible(true);
        button201.setVisible(true);
        button202.setVisible(true);
        button101.setVisible(true);
        button102.setVisible(true);
        button103.setVisible(true);
        button303.setVisible(false);
        button304.setVisible(false);
        button305.setVisible(false);
        button203.setVisible(false);
        button204.setVisible(false);
        button205.setVisible(false);
        button104.setVisible(false);
        button105.setVisible(false);
        door301.setVisible(true);
        door302.setVisible(true);
        door201.setVisible(true);
        door202.setVisible(true);
        door101.setVisible(true);
        door102.setVisible(true);
        door103.setVisible(true);
        door303.setVisible(false);
        door304.setVisible(false);
        door305.setVisible(false);
        door203.setVisible(false);
        door204.setVisible(false);
        door205.setVisible(false);
        door104.setVisible(false);
        door105.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
            
        //});
    //}
public void run() {
                new RoomChoose().setVisible(true);
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button101;
    private javax.swing.JButton button102;
    private javax.swing.JButton button103;
    private javax.swing.JButton button104;
    private javax.swing.JButton button105;
    private javax.swing.JButton button201;
    private javax.swing.JButton button202;
    private javax.swing.JButton button203;
    private javax.swing.JButton button204;
    private javax.swing.JButton button205;
    private javax.swing.JButton button301;
    private javax.swing.JButton button302;
    private javax.swing.JButton button303;
    private javax.swing.JButton button304;
    private javax.swing.JButton button305;
    private javax.swing.JLabel door101;
    private javax.swing.JLabel door102;
    private javax.swing.JLabel door103;
    private javax.swing.JLabel door104;
    private javax.swing.JLabel door105;
    private javax.swing.JLabel door201;
    private javax.swing.JLabel door202;
    private javax.swing.JLabel door203;
    private javax.swing.JLabel door204;
    private javax.swing.JLabel door205;
    private javax.swing.JLabel door301;
    private javax.swing.JLabel door302;
    private javax.swing.JLabel door303;
    private javax.swing.JLabel door304;
    private javax.swing.JLabel door305;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
